
name: Actions

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install tools

      - name: Install dependencies
        run: |
          apt-get install pipenv
          pipenv install --dev

      - name: Black
        run: black --check .

      - name: Mypy
        run: mypy --ignore-missing-imports .


  build:
    runs-on: ubuntu-22.04
    needs: [lint]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get install pipenv
          pipenv install --dev

      - name: Build
        run: mkdocs build

      - name: Upload
        run: ./utils/publish-on-aleph.py

      - uses: actions/upload-artifact@v3
        with:
          name: aleph-docs
          path: site
